book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('guestbook.urls'))
]

guestbook/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('add/', guest_add, name='guest_add'),
    path('update/<int:pk>/', guest_update, name='guest_update'),
    path('delete/<int:pk>/', guest_delete, name='guest_delete'),
]

guestbook/models.py
from django.db import models

class StatusChoice(models.TextChoices):
    ACTIVE = 'active', 'Активно'
    BLOCKED = 'blocked', 'Заблокировано'

class GuestBook(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Имя')
    email = models.EmailField(null=False, blank=False, verbose_name='Почта')
    text = models.TextField(null=False, blank=False, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    updated_at = models.DateTimeField(auto_now=True, null=False, blank=False, verbose_name='Время редактирования')
    status = models.CharField(max_length=20, choices=StatusChoice.choices, default=StatusChoice.ACTIVE,
                              verbose_name='Статус')

    def __str__(self):
        return self.name

guestbook/forms.py
from django import forms
from .models import GuestBook


class GuestForm(forms.ModelForm):
    class Meta:
        model = GuestBook
        fields = ['name', 'email', 'text']

guestbook/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from .models import GuestBook
from .forms import GuestForm
from django.http import HttpResponseRedirect


def index(request):
    guests = GuestBook.objects.filter(status='active').order_by('-created_at')
    return render(request, 'index.html', {'guests': guests})


def guest_add(request):
    if request.method == 'POST':
        form = GuestForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = GuestForm()
    return render(request, 'guest_add.html', {'form': form})


def guest_update(request, pk):
    guest = get_object_or_404(GuestBook, pk=pk)
    if request.method == 'POST':
        form = GuestForm(request.POST, instance=guest)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = GuestForm(instance=guest)
    return render(request, 'guest_update.html', {'form': form, 'guest': guest})


def guest_delete(request, pk):
    guest = get_object_or_404(GuestBook, pk=pk)
    if request.method == 'GET':
        return render(request, 'guest_delete.html', {'guest': guest})
    elif request.method == 'POST':
        guest.delete()
        return redirect('index')

guestbook/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}GuestBook{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/73fa89ad74.js" crossorigin="anonymous"></script>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
            <a class="navbar-brand" href="/">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/add/">Добавить</a>
                </ul>
            </div>
        </div>
    </nav>
</head>
<body>
{% block content %}
{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</body>
</html>

guestbook/templates/guest_delete.html
{% extends 'base.html' %}

{% block content %}
    <style>
        h1 {
            text-align: center;
            padding: 40px;
            color: darkred;
        }
    </style>
    <div class="container">
        <h1>Удалить задачу</h1>
        <h3>Вы уверены, что хотите удалить запись?</h3>
        <form method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Да"/>
        </form>
        <a href="{% url 'index' %}" class="btn btn-secondary">Нет</a>
    </div>
{% endblock %}

guestbook/templates/guest_update.html
{% extends 'base.html' %}

{% block content %}
    <style>
        h1 {
            text-align: center;
            padding: 40px;
            color: black;
        }
    </style>
    <div class="container">
        <h1>Редактировать запись</h1>
        <form method="post">
            {% include 'partial/guestbook_form.html' with button_text='Сохранить' %}
            <div class="row mb-3">
                <div class="col-sm-9 offset-sm-3">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

guestbook/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <style>
        h1 {
            text-align: center;
            padding: 40px;
            color: black;
        }
    </style>
    <div class="container">
        <h1>Гостевая книга</h1>

        <form method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_name" class="form-label">Имя:</label>
                <input type="text" class="form-control" id="id_name" name="name" required>
            </div>
            <div class="mb-3">
                <label for="id_email" class="form-label">Email:</label>
                <input type="email" class="form-control" id="id_email" name="email" required>
            </div>
            <div class="mb-3">
                <label for="id_text" class="form-label">Текст:</label>
                <textarea class="form-control" id="id_text" name="text" required></textarea>
            </div>
            <button type="submit" class="btn btn-danger">Добавить запись</button>
        </form>

        <div class="row">
            {% for guest in guests %}
                <div class="col-md-4 mb-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <div>
                                <a class="btn-primary" href="{% url 'guest_update' guest.pk %}">
                                    <i class="fas fa-solid fa-pen-to-square"></i>
                                </a>
                                <a class="btn-primary" href="{% url 'guest_delete' guest.pk %}">
                                    <i class="fas fa-solid fa-user-minus"></i>
                                </a>
                            </div>
                            <h5 class="card-title">{{ guest.name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ guest.email }}</h6>
                            <p class="card-text">{{ guest.text }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

guestbook/templates/partial/guestbook_form.html
<form method="POST">
    {% csrf_token %}
    <div class="row mb-3">
        <label for="id_name" class="col-sm-3 col-form-label text-end">Имя:</label>
        <div class="col-sm-9">
            {{ form.name }}
        </div>
    </div>

    <div class="row mb-3">
        <label for="id_email" class="col-sm-3 col-form-label text-end">Email:</label>
        <div class="col-sm-9">
            {{ form.email }}
        </div>
    </div>

    <div class="row mb-3">
        <label for="id_text" class="col-sm-3 col-form-label text-end">Текст:</label>
        <div class="col-sm-9">
            {{ form.text }}
        </div>
    </div>


    <div class="row mb-3">
        <div class="col-sm-9 offset-sm-3">
            <button type="submit" class="btn btn-secondary">Добавить</button>
        </div>
    </div>
</form>